# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-TagCloud-Extended
version:      0.08
version_from: lib/HTML/TagCloud/Extended.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Class::Data::Inheritable:      0
    Readonly:                      0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.29
